export type VisaType = "visa-free" | "evisa" | "eta" | "visa-required";

export interface VisaCountry {
  name: string;
  slug: string;
  type: VisaType;
  /** e-visa, tourist, business, etc. */
  visaCategory: string;
  maxStay: string;
  processingTime: string;
  visaFee: string;
  serviceFee: string;
  requirements: string[];
  notes?: string;
  region: string;
}

export const visaCountries: VisaCountry[] = [
  // ── VISA-FREE ──
  { name: "Tanzania", slug: "tanzania", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "South Africa", slug: "south-africa", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Mauritius", slug: "mauritius", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Ghana", slug: "ghana", type: "visa-free", visaCategory: "Visitor", maxStay: "60 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Benin", slug: "benin", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Botswana", slug: "botswana", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "DR Congo", slug: "dr-congo", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Eswatini", slug: "eswatini", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Gambia", slug: "gambia", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Lesotho", slug: "lesotho", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Malawi", slug: "malawi", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Mozambique", slug: "mozambique", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Namibia", slug: "namibia", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Rwanda", slug: "rwanda", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Uganda", slug: "uganda", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Zambia", slug: "zambia", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Africa", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Hong Kong", slug: "hong-kong", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Iran", slug: "iran", type: "visa-free", visaCategory: "Visitor", maxStay: "15 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Malaysia", slug: "malaysia", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Philippines", slug: "philippines", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Singapore", slug: "singapore", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Palestine", slug: "palestine", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Asia", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Ecuador", slug: "ecuador", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Bahamas", slug: "bahamas", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Barbados", slug: "barbados", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Dominica", slug: "dominica", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Haiti", slug: "haiti", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Saint Kitts & Nevis", slug: "saint-kitts-nevis", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Saint Vincent & Grenadines", slug: "saint-vincent-grenadines", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Trinidad & Tobago", slug: "trinidad-tobago", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "British Virgin Islands", slug: "british-virgin-islands", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Montserrat", slug: "montserrat", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Americas", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Cook Islands", slug: "cook-islands", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Fiji", slug: "fiji", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Micronesia", slug: "micronesia", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Niue", slug: "niue", type: "visa-free", visaCategory: "Visitor", maxStay: "30 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Samoa", slug: "samoa", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },
  { name: "Vanuatu", slug: "vanuatu", type: "visa-free", visaCategory: "Visitor", maxStay: "90 days", processingTime: "—", visaFee: "Free", serviceFee: "—", region: "Oceania", requirements: ["Valid passport (6+ months validity)"] },

  // ── E-VISA / ETA ──
  { name: "Kenya", slug: "kenya", type: "eta", visaCategory: "ETA (Online)", maxStay: "90 days", processingTime: "72 hours", visaFee: "Free", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport — soft copy of bio page", "Passport-sized photo", "Flight and accommodation itinerary", "Contact details"] },
  { name: "Ethiopia", slug: "ethiopia", type: "evisa", visaCategory: "eVisa / Visa on Arrival", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$50", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport", "Return ticket", "Accommodation booking"] },
  { name: "Gabon", slug: "gabon", type: "eta", visaCategory: "ETA (Online)", maxStay: "90 days", processingTime: "72 hours", visaFee: "€70 + €15 processing (single)", serviceFee: "Contact us", region: "Africa", requirements: ["Online application form", "Copy of passport data page (6+ months validity)", "Color photograph (35×45mm, less than 6 months old)"] },
  { name: "Burkina Faso", slug: "burkina-faso", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "33,000 CFA (standard) / 104,500 CFA (express)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "Online application form", "2 passport-style photos (white background)", "Proof of onward travel", "Yellow fever vaccination", "Medical certificate + proof of funds (may be requested)"] },
  { name: "Cameroon", slug: "cameroon", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$181.82 (3-day) / US$272.73 (24hr)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months, 1 blank page)", "Passport-sized colour photo", "Return flight/cruise booking", "Completed application form", "Yellow fever vaccination proof", "Invitation letter / accommodation proof (if needed)"] },
  { name: "Chad", slug: "chad", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$150 (1-month single) / US$200 (3-month multiple)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months, 2 blank pages)", "Completed + signed application form", "2 passport-style photos (white background)", "Return ticket / onward travel proof", "Hotel reservation or invitation letter", "Yellow fever vaccination certificate"] },
  { name: "Djibouti", slug: "djibouti", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$23 (single entry)", serviceFee: "Contact us", region: "Africa", requirements: ["Scanned passport (6+ months validity)", "Passport-style colour photo", "Round-trip flight reservation", "Accommodation proof", "Invitation letter (if visiting family/friends)"] },
  { name: "Ivory Coast", slug: "ivory-coast", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "€75", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "Passport-style photograph", "Proof of accommodation", "Return ticket / itinerary", "Yellow fever vaccination certificate"] },
  { name: "Nigeria", slug: "nigeria", type: "evisa", visaCategory: "eVisa on Arrival", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$20", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "Digital passport-style photo", "Proof of accommodation", "Return flight ticket", "Evidence of sufficient funds"] },
  { name: "South Sudan", slug: "south-sudan", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$160", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "Passport-sized photo", "Yellow fever vaccination proof", "Travel itinerary (accommodation + return ticket)", "Completed visa application form", "Invitation letter + company docs (for business)"] },
  { name: "Togo", slug: "togo", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "From 25,000 CFA", serviceFee: "Contact us", region: "Africa", requirements: ["Online application form", "Scanned passport (3+ months beyond visa)", "Recent passport photo", "Flight reservation", "Travel insurance (recommended)", "Hotel reservation (recommended)"] },
  { name: "Morocco", slug: "morocco", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "770 MAD (standard) / 1,100 MAD (express)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "Passport-style photos", "Proof of onward/return travel", "Proof of financial means (€7/day minimum)"] },
  { name: "India", slug: "india", type: "evisa", visaCategory: "e-Tourist / e-Business Visa", maxStay: "30 days to 5 years", processingTime: "5 working days", visaFee: "Varies", serviceFee: "Contact us", region: "Asia", requirements: ["Scanned bio page of passport", "Recent personal photo", "Business card + invitation (for business)", "Apply at least 4 days before arrival", "Non-extendable, non-convertible"] },
  { name: "Armenia", slug: "armenia", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "21 or 120 days", processingTime: "3 working days", visaFee: "US$6 (21 days) / US$30 (120 days)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Passport-style photo (digital)", "Proof of flight + accommodation", "Online application form", "Credit/debit card for payment"] },
  { name: "Bahrain", slug: "bahrain", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "Up to 90 days", processingTime: "3-5 working days", visaFee: "5 BHD (single) / 25 BHD (multiple)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Proof of funds (bank statement)", "Return/onward ticket", "Hotel booking or accommodation proof", "Online application form", "Passport-sized photos"] },
  { name: "Cambodia", slug: "cambodia", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$30 (Tourist) / US$35 (Business)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months, 1 blank page)", "Digital photo (JPEG/PNG)", "Credit card for online payment", "Completed online application"] },
  { name: "Georgia", slug: "georgia", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$20", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Digital passport photo (JPEG, white/light background)", "Proof of travel purpose (invitation, business meeting)", "Proof of accommodation", "Proof of sufficient funds", "Travel health insurance", "Round-trip flight ticket"] },
  { name: "Kyrgyzstan", slug: "kyrgyzstan", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$51.50 (1-month single)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months, 2 blank pages)", "Digital photo (white background)", "Online application form", "Credit/debit card", "Invitation letter (if needed)", "Scanned passport + photo"] },
  { name: "Myanmar", slug: "myanmar", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "28–70 days", processingTime: "3-5 working days", visaFee: "US$50 (tourist) / US$70 (business)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Colour photo (4.6×3.8 cm, taken within 3 months)", "Passport bio-data page upload", "Return ticket proof", "Hotel booking proof"] },
  { name: "Pakistan", slug: "pakistan", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days (single)", processingTime: "3-5 working days", visaFee: "Varies", serviceFee: "Contact us", region: "Asia", requirements: ["Photograph", "Passport", "Hotel booking details"] },
  { name: "Qatar", slug: "qatar", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "72 hours", visaFee: "US$30", serviceFee: "Contact us", region: "Asia", requirements: ["Online application form", "Copy of passport data page (6+ months)", "Color photograph (35×45mm, less than 6 months)"] },
  { name: "Russia", slug: "russia", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "16 days per entry (60-day validity)", processingTime: "3-5 working days", visaFee: "US$52", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months, 1 blank page)", "Digital passport-style photo", "Travel medical insurance (valid in Russia)", "Online application form", "Credit/debit card for payment"] },
  { name: "Sri Lanka", slug: "sri-lanka", type: "evisa", visaCategory: "ETA (Online)", maxStay: "30 days (double entry)", processingTime: "3-5 working days", visaFee: "US$50", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "ETA approval before travel", "Onward/return ticket", "Proof of sufficient funds", "Hotel accommodation or invitation", "Passport-size photo (35×45mm)"] },
  { name: "Vietnam", slug: "vietnam", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "US$25 (single) / US$50 (multiple)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months, 2 blank pages)", "Clear scan of passport bio page", "Passport-style photo (4×6 cm, white background)", "Valid email address", "Credit/debit card for payment", "Travel itinerary (flights + accommodation)"] },
  { name: "Colombia", slug: "colombia", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "Up to 90 days", processingTime: "3-5 working days", visaFee: "US$100 (incl. stamp tax)", serviceFee: "Contact us", region: "Americas", requirements: ["Completed visa application form", "Valid passport + 2 blank pages", "2 recent 3×3 cm photos (white background)", "Copy of passport main page", "Documents certifying activity in Colombia", "Proof of financial capacity", "Invitation letter (if applicable)", "Return/onward ticket"] },
  { name: "Suriname", slug: "suriname", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "€50 (single) / €75 (multiple)", serviceFee: "Contact us", region: "Americas", requirements: ["Passport bio page", "Itinerary (not ticket)", "Accommodation reservation", "Photo 3×4 cm", "Business: reference letter + Chamber of Commerce certificate"] },
  { name: "Australia", slug: "australia", type: "evisa", visaCategory: "eVisa", maxStay: "12 months (Visitor 600)", processingTime: "10-30 working days", visaFee: "AUD 195", serviceFee: "Contact us", region: "Oceania", requirements: ["Valid passport (6+ months)", "Proof of identity", "Visa application form", "Biometrics (fingerprints + photo)", "Evidence of ties to Zimbabwe", "Financial resources proof", "Travel itinerary", "Invitation letter (if applicable)", "Police certificate (if needed)"] },
  { name: "New Zealand", slug: "new-zealand", type: "evisa", visaCategory: "NZeTA", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "NZD 300 + NZD 100 IVL", serviceFee: "Contact us", region: "Oceania", requirements: ["Valid passport", "NZeTA approval", "Proof of onward travel", "Sufficient funds proof", "Good health + good character", "Genuine visit intent"] },
  { name: "Moldova", slug: "moldova", type: "evisa", visaCategory: "eVisa (Online)", maxStay: "90 days", processingTime: "3-5 working days", visaFee: "€40", serviceFee: "Contact us", region: "Europe", requirements: ["Application form", "Valid passport (10 yrs, 3+ months beyond stay)", "Colour photo 35×45mm", "Invitation (if required) or EU/US/UK/Schengen visa copy", "Hotel reservation or accommodation commitment", "Round-trip ticket", "Proof of means (€30/day, min €300)", "Travel medical insurance (€30k+)"] },

  // ── VISA REQUIRED ──
  { name: "China", slug: "china", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "90 days", processingTime: "5-15 working days", visaFee: "US$45 (single) / US$68 (multiple)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Passport photo (48×33mm, white background)", "Completed Chinese visa form", "Bank statement (3+ months)", "Supporting documents", "Sponsor letter + bank statement + relationship proof (if sponsored)"] },
  { name: "Japan", slug: "japan", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "5-15 working days", visaFee: "US$22 (single) / US$43 (multiple)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Visa application form", "Passport-sized photo (4.5×4.5cm)", "3 months bank statement (original)", "Detailed itinerary + daily schedule", "Confirmed letter of employment", "Hotel reservation + flight tickets", "Must apply in person"] },
  { name: "South Korea", slug: "south-korea", type: "visa-required", visaCategory: "Tourist / Business Visa", maxStay: "Up to 90 days", processingTime: "7-14 working days", visaFee: "US$40", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "Passport-sized photo on application form", "3 months bank statement (min US$3,000 for 7 days)", "Flight + hotel bookings", "Itinerary of activities in Korea", "Letter from employer / proof of funds", "Invitation + host docs (if visiting someone)"] },
  { name: "Thailand", slug: "thailand", type: "visa-required", visaCategory: "e-Visa (Tourist)", maxStay: "30-60 days", processingTime: "5-10 working days", visaFee: "1,600 THB (transit) / 2,000 THB (tourist)", serviceFee: "Contact us", region: "Asia", requirements: ["Passport bio-data page", "Passport-sized photo (last 6 months)", "Document indicating current location", "Travel booking confirmation", "Proof of accommodation in Thailand", "Financial evidence (min US$2,000)"] },
  { name: "Indonesia", slug: "indonesia", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "30 days", processingTime: "5-10 working days", visaFee: "US$99 (single entry)", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (6+ months)", "3 passport-style photos (48×33mm)", "Completed visa form", "Bank statement (3+ months, min US$2,000)", "Travel insurance"] },
  { name: "Turkey", slug: "turkey", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "15-30 working days", visaFee: "US$200 (single entry)", serviceFee: "US$30", region: "Asia", requirements: ["Passport (9+ months validity)", "1 biometric photo (5×5cm, white background, last 6 months)", "6 months bank statement (min US$2,000)", "Hotel reservation or invitation letter", "Flight reservation", "Police clearance (14+ yrs)", "Parental affidavit (if under 18)"] },
  { name: "Bangladesh", slug: "bangladesh", type: "visa-required", visaCategory: "Tourist / Business Visa", maxStay: "30 days – 1 year", processingTime: "7 working days", visaFee: "US$70 (tourist) / US$160 (business/multiple)", serviceFee: "US$50", region: "Asia", requirements: ["Valid passport (6+ months)", "Passport-type photograph", "Clear scan of passport info page", "Proof of accommodation", "Proof of sufficient funds", "Travel medical insurance", "Travel itinerary or invitation letter", "Host contact details"] },
  { name: "Egypt", slug: "egypt", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "7 working days", visaFee: "US$25", serviceFee: "US$20", region: "Africa", requirements: ["Valid passport (6+ months)", "Completed visa application form", "Copy of main passport page", "Copy of round-trip tickets", "Copy of hotel booking", "Invitation letter from Egypt-based entity", "Confirmation of employment", "Daily schedule"] },
  { name: "Jordan", slug: "jordan", type: "visa-required", visaCategory: "Tourist eVisa", maxStay: "Up to 3 months", processingTime: "2 working days", visaFee: "US$56", serviceFee: "Contact us", region: "Asia", requirements: ["Fully electronic — no documents to mail", "Receive e-visa via email"] },
  { name: "Israel", slug: "israel", type: "visa-required", visaCategory: "Tourist Visa (B/2)", maxStay: "Up to 90 days", processingTime: "10 working days", visaFee: "R 515 + VFS fees", serviceFee: "Contact us", region: "Asia", requirements: ["Valid passport (3+ months beyond visa)", "Filled + signed application", "3 months bank statements", "Confirmation of employment", "Place of stay (hotel/rental)", "Return flight tickets", "Planned itinerary", "Medical insurance", "2 colour photos (5×5cm, white background)"] },
  { name: "USA", slug: "usa", type: "visa-required", visaCategory: "B1/B2 Visitor Visa", maxStay: "1 year", processingTime: "Interview-based", visaFee: "US$185", serviceFee: "US$150", region: "Americas", requirements: ["Valid passport (6+ months beyond stay)", "DS-160 confirmation page", "Passport-sized photo (US visa specs)", "Visa fee receipt", "Proof of ties to Zimbabwe (employment, family, property)", "Financial evidence (bank statements)", "Detailed travel itinerary", "Bond: US$5,000–US$15,000"] },
  { name: "Canada", slug: "canada", type: "visa-required", visaCategory: "Visitor Visa", maxStay: "6 months – 10 years", processingTime: "17–139 working days", visaFee: "US$100", serviceFee: "US$50", region: "Americas", requirements: ["Valid passport (6+ months beyond departure)", "1 blank page for visa stamp", "Visa application form", "Proof of funds", "Proof of ties to Zimbabwe", "Letter of invitation (if applicable)", "Travel itinerary", "Biometrics (fingerprints + photo)", "Good health + no criminal convictions"] },
  { name: "Mexico", slug: "mexico", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "10 working days", visaFee: "US$54 (cash)", serviceFee: "Contact us", region: "Americas", requirements: ["Passport-sized photo (4.5×3.5cm, no glasses, white bg)", "Valid passport (6+ months) + colour copy", "Legal residence in South Africa", "3 months personal bank statements (stamped)", "3 months payslips or invoices", "Employment letter on company letterhead", "OR sponsorship documents with financial solvency"] },
  { name: "Brazil", slug: "brazil", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "5 working days", visaFee: "US$80 (bank deposit)", serviceFee: "Contact us", region: "Americas", requirements: ["Original passport (6+ months, 2 blank visa pages)", "Completed + signed application form", "Unpaid hotel reservation", "Letter from employer (on letterhead)", "3 months personal bank statements", "Invitation letter (if applicable)", "Min US$100/day free funds", "Parental consent + docs (if under 18)"] },
  { name: "UK", slug: "uk", type: "visa-required", visaCategory: "Standard Visitor Visa", maxStay: "6 months", processingTime: "15-40 working days", visaFee: "£127 (6-month) to £1,059 (10-year)", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (6+ months beyond stay)", "Completed application form", "Proof of financial resources (bank statements)", "Detailed travel itinerary", "Proof of legal residence in Zimbabwe", "Return ticket or intent to return", "Invitation letter (if applicable)", "VFS uploading fee: US$50"] },
  { name: "Ireland", slug: "ireland", type: "visa-required", visaCategory: "Short Stay (C)", maxStay: "Up to 90 days", processingTime: "30-50 working days", visaFee: "€60 (single) / €100 (multiple)", serviceFee: "US$100 (individual) / US$50 (group 9+)", region: "Europe", requirements: ["Valid passport (6+ months, 2 blank pages)", "Recent passport photos (white background, <3 months)", "6 months bank statements", "Employment letter + salary certificate", "Detailed application letter + travel itinerary", "Accommodation bookings", "Parental consent + birth certificate (if under 18)"] },
  { name: "Spain", slug: "spain", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed Schengen application form", "Passport-sized colour photo (white background)", "Valid passport (3+ months beyond exit, 2 blank pages)", "Travel medical insurance (€30k+, Schengen-wide)", "Visa fee payment", "Documents proving purpose of travel + financial means", "Proof of residence in consular district"] },
  { name: "France / Belgium / Monaco", slug: "france-belgium-monaco", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (3+ months beyond stay, <10 yrs old)", "Completed + signed visa application form", "2 passport-sized photos", "Proof of sufficient funds (bank statements, payslips)", "Travel insurance (€30k+, Schengen-wide)", "Letter explaining trip purpose", "Accommodation reservations or invitation letter", "Employer letter / No objection statement", "Proof of residence in Zimbabwe", "Round-trip tickets"] },
  { name: "Netherlands / Norway / Luxembourg", slug: "netherlands-norway-luxembourg", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 + VFS US$89", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (3+ months after exit, 2 blank pages)", "Completed + signed application form", "2 recent passport-sized photos", "Proof of legal residence in Zimbabwe", "Proof of sufficient funds", "Travel insurance (€30k+)", "Return ticket", "Accommodation proof"] },
  { name: "Italy", slug: "italy", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90", serviceFee: "US$70", region: "Europe", requirements: ["Valid passport (3+ months beyond stay, <10 yrs)", "Completed + signed visa application form", "Passport-sized photo", "Travel insurance (€30k+, Schengen-wide)", "Hotel reservation or invitation letter", "3 months bank statements + payslips", "Proof of return/onward travel", "Cover letter outlining purpose of visit", "Employer letter (if applicable)"] },
  { name: "Austria", slug: "austria", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 + VFS US$89", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed Austria visa application form", "Valid passport (2 blank pages, 3+ months after exit)", "Passport photo meeting Austria requirements", "Proof of financial means (bank statements, pay slips)", "Proof of onward travel (round-trip tickets)", "Hotel reservations or invitation letter", "Cover letter explaining travel purpose", "Travel insurance (€30k+, Schengen-wide)", "Employer letter + No objection statement"] },
  { name: "Greece", slug: "greece", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 (cash)", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (6+ months after trip end)", "Travel insurance (€30k+, Schengen-wide, +3-5 days)", "Travel itinerary + purpose (bookings, no tickets)", "Proof of employment/business/income + bank letter", "Title deeds (if property owner)", "Parental consent affidavits (if travelling with child)", "1 coloured photograph", "Must apply in person at Embassy"] },
  { name: "Poland", slug: "poland", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 (debit card)", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed visa application form", "Original passport (2 blank pages, 3+ months, <10 yrs)", "2 passport-type photos (35×45mm, white bg)", "Copies of previous visas (if applicable)", "Cover letter explaining purpose", "Booked flight itinerary", "Hotel reservation", "Proof of civil status", "Proof of financial means (€67.76/3 days, €22.59/day after)", "Travel insurance (€30k+)"], notes: "Additional docs per employment status: employed → contract + 6-month bank statement + leave letter + ITR; self-employed → business license + company statement + ITR; student → enrolment + no-objection; retired → 6-month pension statement" },
  { name: "Portugal", slug: "portugal", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 (debit card)", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed visa application form", "Valid passport (2 blank pages, <10 yrs, 3+ months beyond exit)", "2 identical passport-type photos (35×45mm)", "Copies of previous visas (if applicable)", "Cover letter", "Booked flight itinerary", "Proof of accommodation", "Proof of civil status", "Proof of financial means", "Travel insurance (€30k+)"] },
  { name: "Hungary", slug: "hungary", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 (debit card)", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed visa application form", "Original passport (2 blank pages, <10 yrs, 3+ months beyond exit)", "2 identical passport-type photos (35×45mm)", "Copies of previous visas (if applicable)", "Cover letter", "Booked flight itinerary", "Proof of accommodation", "Proof of civil status", "Proof of financial means", "Travel insurance (€30k+)"] },
  { name: "Luxembourg", slug: "luxembourg-visa", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "10-30 working days", visaFee: "€90 (debit card)", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed visa application form", "Valid passport (2 blank pages, 3+ months beyond exit, <10 yrs)", "2 identical passport-type photos (35×45mm)", "Copies of previous visas (if applicable)", "Cover letter", "Return flight ticket", "Proof of accommodation", "Proof of civil status", "6 months bank statements", "Travel insurance (€30k+)"] },
  { name: "Czech Republic", slug: "czech", type: "visa-required", visaCategory: "Tourist (Schengen)", maxStay: "90 days", processingTime: "30 working days (Zimbabweans)", visaFee: "€90 (credit card)", serviceFee: "Contact us", region: "Europe", requirements: ["Completed + signed visa application form", "Valid passport (6+ months, <10 yrs)", "Passport photo (face ≥80% frame, white bg)", "Flight ticket", "Hotel reservation", "Travel medical insurance (€30k+, Schengen-wide)", "3 months bank statement", "Letter from employer", "Pay slips for last 3 months (optional)", "Photocopy of passport bio + last page"] },
  { name: "Cyprus", slug: "cyprus", type: "visa-required", visaCategory: "Visitor Visa", maxStay: "Up to 90 days", processingTime: "15-30 working days", visaFee: "€90 (single & multiple)", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (3+ months after exit, <10 yrs, 3 blank pages)", "Completed + signed application form", "2 recent colour photos (4.13×5.31cm)", "Provisional booking/itinerary (no tickets before visa)", "Hotel reservation on letterhead", "3 months bank statements", "Recent employer letter (on letterhead, proof of salary)", "Medical insurance (€30k+, no excess)", "Parental consent (if minor)"] },
  { name: "Ukraine", slug: "ukraine", type: "visa-required", visaCategory: "Visitor Visa", maxStay: "Up to 90 days", processingTime: "7-10 working days", visaFee: "US$24 + US$75 service charge", serviceFee: "Contact us", region: "Europe", requirements: ["Valid passport (30+ days after stay, 2 blank pages)", "2 recent passport-size photos (35×45mm)", "Completed DHA-84 form (handwritten, black ink)", "Yellow fever vaccination (if applicable)", "3 months certified bank statement (<7 days old)", "No fixed flight before visa issued", "Certified supporting documents", "Invitation letter from host + SA ID/permit copy", "Covering letter signed by applicant"] },
  { name: "Angola", slug: "angola", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "5 working days", visaFee: "US$250 (bank deposit)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (7+ months)", "2 passport-style photos", "Invitation letter", "Hotel reservation", "Return flight ticket", "Bank statement (min US$200)", "Yellow fever card (original + copy)", "Tourist visa form"] },
  { name: "Sudan", slug: "sudan", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "5 working days", visaFee: "US$54 (bank deposit)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "3 passport-style photos", "Invitation letter", "Current bank statement", "Medical certificate for infectious diseases", "Tourist visa form (on application day)"] },
  { name: "Algeria", slug: "algeria", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "5 working days", visaFee: "US$50 (bank deposit)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months)", "2 passport-style photos", "Invitation letter", "Travel itinerary / copy of ticket", "Medical certificate for infectious diseases", "2 tourist visa forms"] },
  { name: "Venezuela", slug: "venezuela", type: "visa-required", visaCategory: "Tourist Visa", maxStay: "Up to 90 days", processingTime: "15-30 working days", visaFee: "US$50", serviceFee: "Contact us", region: "Americas", requirements: ["Valid passport (6+ months, blank visa pages)", "Completed + signed application form", "Passport-type photo (no homemade digital)", "Proof of permanent residence / visa status", "Letter of request with flight + accommodation details", "Copy of airline tickets + accommodation", "Proof of employment (length, position, salary)", "6 months bank statements", "Bank reference letter (stamped)", "Valid police clearance (<6 months)", "Proof of US$50 payment", "Yellow fever certificate (suggested)"], notes: "Apply at least 30 days before travel" },
  { name: "Morocco (Sticker)", slug: "morocco-sticker", type: "visa-required", visaCategory: "Tourist (Sticker)", maxStay: "Up to 90 days", processingTime: "10-15 working days", visaFee: "R 802 (single) / R 1,203 (multiple)", serviceFee: "Contact us", region: "Africa", requirements: ["Valid passport (6+ months beyond stay)", "Completed application form", "Proof of accommodation", "Proof of onward travel (return ticket)", "Proof of sufficient funds", "Residency proof (if non-Zimbabwean)"] },
];

export const regions = ["All", "Africa", "Asia", "Europe", "Americas", "Oceania"] as const;

export const visaTypeLabels: Record<VisaType, { label: string; badge: string }> = {
  "visa-free": { label: "Visa Free", badge: "bg-green-100 text-green-700" },
  evisa: { label: "e-Visa", badge: "bg-blue-100 text-blue-700" },
  eta: { label: "ETA", badge: "bg-cyan-100 text-cyan-700" },
  "visa-required": { label: "Visa Required", badge: "bg-amber-100 text-amber-700" },
};

export function getVisaTypeLabel(type: VisaType): string {
  return visaTypeLabels[type].label;
}
