import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, Building, Store } from "lucide-react";
export const metadata: Metadata = { title: "Dubai — ArcTravel", description: "Ultra-modern city with world-class shopping, dining, desert safaris, and architectural wonders." };
const highlights = [
  { icon: Building, title: "Burj Khalifa & Downtown", desc: "Stand atop the world's tallest building. Explore Dubai Mall, the Dubai Fountain, and the Souk Al Bahar." },
  { icon: Sun, title: "Desert Safari", desc: "Dune bashing, camel rides, sandboarding, and a BBQ dinner under the stars in the Arabian desert." },
  { icon: Store, title: "Gold Souk & Traditional Dubai", desc: "Visit the Gold Souk, Spice Souk, and take an abra (water taxi) across Dubai Creek to the old quarter." },
  { icon: Building, title: "Beaches & Resorts", desc: "Jumeirah Beach, Palm Jumeirah, and Atlantis — world-class beach clubs, waterparks, and luxury resorts." },
];
const tips = ["Best time: November to March (cooler, 20-30°C)", "Visa on arrival for many nationalities (check before travel)", "Dubai is conservative — dress modestly in public areas and malls", "Weekend is Friday-Saturday; Sunday is a working day", "Uber and Careem are widely available and affordable"];
export default function DubaiPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#5a3d1a] via-[#7a5533] to-[#6b4a28] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />United Arab Emirates</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Dubai</h1><p className="mt-4 text-lg text-white/75">Ultra-modern city with world-class shopping, dining, desert safaris, and architectural wonders.</p><Link href="/book" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Plan Dubai <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">Dubai Highlights</h2><p className="mt-2 text-center text-muted-foreground">Modern marvels meet Arabian tradition</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><Building className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">Dubai Calling?</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">A stopover or a full holiday — we'll handle flights, hotels, transfers, and activities.</p><Link href="/book"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Book Now</Button></Link></div></div></section>
    </>
  );
}
