import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, Waves, Mountain } from "lucide-react";
export const metadata: Metadata = { title: "Bali — ArcTravel", description: "Tropical island paradise with ancient temples, rice terraces, surf beaches, and rich spiritual culture." };
const highlights = [
  { icon: Mountain, title: "Ubud & Rice Terraces", desc: "The spiritual heart of Bali — monkey forest, Tegallalang rice terraces, yoga retreats, and traditional crafts." },
  { icon: MapPin, title: "Temples & Culture", desc: "Tanah Lot, Uluwatu, Besakih — ancient sea temples perched on cliffs, with mesmerising kecak fire dances." },
  { icon: Waves, title: "Beaches & Surf", desc: "Seminyak, Canggu, Uluwatu — world-class surf breaks, beach clubs, sunsets, and coastal dining." },
  { icon: Sun, title: "Wellness & Retreats", desc: "Bali is a global wellness destination — yoga, meditation, spa treatments, and plant-based cuisine." },
];
const tips = ["Best time: April to October (dry season, sunny)", "Visa on arrival for many nationalities (US$35, 30 days, extendable)", "Rent a scooter or hire a driver — it's the best way to get around", "Dress modestly when visiting temples (sarong and sash required)", "Bali is more affordable than you think — great value for accommodation and food"];
export default function BaliPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#1b4d2e] via-[#2d6b45] to-[#1f5a37] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />Indonesia</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Bali</h1><p className="mt-4 text-lg text-white/75">Tropical island paradise with ancient temples, rice terraces, surf beaches, and spiritual culture.</p><Link href="/book?destination=Bali&notes=Bali+destination+page" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Plan Bali <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">Bali Experiences</h2><p className="mt-2 text-center text-muted-foreground">Spirituality, nature, surf, and serenity</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><Waves className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">Island of the Gods</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Flights, villas, drivers, and experiences — we'll create your perfect Bali itinerary.</p><Link href="/book?destination=Bali&notes=Bali+destination+page"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Book Bali</Button></Link></div></div></section>
    </>
  );
}
