import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, TreePalm, Compass } from "lucide-react";
export const metadata: Metadata = { title: "Nairobi & Maasai Mara — ArcTravel", description: "East Africa's safari capital — the Great Migration, Maasai culture, and vibrant urban energy." };
const highlights = [
  { icon: TreePalm, title: "Maasai Mara Safari", desc: "Witness the Great Migration (July-October), the Big Five, and vast open plains that define the African safari experience." },
  { icon: Compass, title: "Maasai Village Visit", desc: "Meet the Maasai people in their manyattas — learn about their traditions, dancing, and way of life." },
  { icon: MapPin, title: "Nairobi City", desc: "The Green City in the Sun — Nairobi National Park (safari with city skyline), Giraffe Centre, Karen Blixen Museum, and great restaurants." },
  { icon: Sun, title: "Amboseli & Other Parks", desc: "Extensions to Amboseli (Mt Kilimanjaro views), Lake Nakuru (flamingos), and Tsavo — endless safari combinations." },
];
const tips = ["Best time for Mara: July to October (Great Migration river crossings)", "Visa on arrival or e-visa available (apply online before travel)", "Nairobi is high altitude — stays cool year-round; pack a jacket", "Combine with a Zanzibar beach extension for the perfect Kenya + beach holiday", "Book safari camps well in advance for peak migration season"];
export default function NairobiMaasaiMaraPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#5a3d1a] via-[#6b4a20] to-[#4a3010] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />Kenya</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Nairobi &amp; Maasai Mara</h1><p className="mt-4 text-lg text-white/75">East Africa's safari capital — the Great Migration, Maasai culture, and vibrant urban energy.</p><Link href="/book" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Plan Your Safari <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">Kenya Highlights</h2><p className="mt-2 text-center text-muted-foreground">Safaris, culture, and city life</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><TreePalm className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">Witness the Mara?</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">The Great Migration is one of nature's greatest spectacles. Let us plan your Kenyan adventure.</p><Link href="/book"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Start Planning</Button></Link></div></div></section>
    </>
  );
}
