import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, Waves, Compass } from "lucide-react";
export const metadata: Metadata = { title: "Zanzibar — ArcTravel", description: "Tropical paradise with white-sand beaches, turquoise waters, spice farms, and Stone Town's rich history." };
const highlights = [
  { icon: Waves, title: "Beaches & Resorts", desc: "Pristine white-sand beaches on the east coast — Nungwi, Kendwa, and Paje. Swim, snorkel, dhow cruises, and chill." },
  { icon: Compass, title: "Stone Town", desc: "A UNESCO World Heritage site — narrow alleyways, carved doors, spice markets, and centuries of Swahili culture." },
  { icon: Sun, title: "Spice Tours", desc: "Zanzibar is the Spice Island. Visit plantations for cloves, nutmeg, cinnamon, and vanilla — with fresh fruit tastings." },
  { icon: Waves, title: "Mnemba Atoll", desc: "A protected marine reserve off the northeast coast. World-class snorkelling and diving with turtles, rays, and reef fish." },
];
const tips = ["Best time: June to October (dry, cool) or December to February (warm, clear)", "Visa on arrival for most nationalities (US$50 single entry)", "Dress modestly in Stone Town out of respect for the local culture", "Try Zanzibari cuisine — seafood curries, biryani, and fresh sugarcane juice", "Combine with a Tanzania safari (Serengeti / Ngorongoro) for the ultimate trip"];
export default function ZanzibarPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#0a5c7a] via-[#0d7a9a] to-[#0a6a8a] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />Tanzania — Zanzibar Archipelago</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Zanzibar</h1><p className="mt-4 text-lg text-white/75">White sands, turquoise waters, spice farms, and Stone Town's rich history.</p><Link href="/book" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Book Zanzibar <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">Island Experiences</h2><p className="mt-2 text-center text-muted-foreground">Beach, culture, spice, and marine adventures</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><Waves className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">Paradise Awaits</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Tell us your dates — we'll handle flights, resort, transfers, and excursions.</p><Link href="/book"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Book Your Escape</Button></Link></div></div></section>
    </>
  );
}
