import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, Building, Landmark } from "lucide-react";
export const metadata: Metadata = { title: "London — ArcTravel", description: "Historic and vibrant — royal landmarks, world-class museums, theatre, and diverse neighbourhoods to explore." };
const highlights = [
  { icon: Landmark, title: "Royal London", desc: "Buckingham Palace, Westminster Abbey, the Tower of London, and the Changing of the Guard." },
  { icon: Building, title: "Museums & Galleries", desc: "The British Museum, Natural History Museum, Tate Modern, and the V&A — most are free to enter." },
  { icon: MapPin, title: "Neighbourhoods & Markets", desc: "Camden Market, Borough Market, Notting Hill, Shoreditch, and Covent Garden — each with its own character." },
  { icon: Sun, title: "Theatre & Nightlife", desc: "West End theatre, comedy clubs, rooftop bars, and live music venues across Soho and the South Bank." },
];
const tips = ["Best time: May to September (warmer, longer days, outdoor events)", "UK Standard Visitor visa required for Zimbabwe passport holders (apply well in advance)", "The Tube is the fastest way around — get an Oyster card for cheaper fares", "Book West End shows and popular restaurants in advance", "Many museums are free — plan which ones you want to prioritise"];
export default function LondonPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#2a2a3a] via-[#3a3a4a] to-[#2a2a3a] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />United Kingdom — England</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">London</h1><p className="mt-4 text-lg text-white/75">Historic and vibrant — royal landmarks, world-class museums, theatre, and diverse neighbourhoods.</p><Link href="/book?destination=London&notes=London+destination+page" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Plan London <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">London Highlights</h2><p className="mt-2 text-center text-muted-foreground">Royalty, culture, food, and energy</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><Landmark className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">London Calling?</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Flights, hotels, visa assistance, and a custom itinerary — we've got London covered.</p><Link href="/book?destination=London&notes=London+destination+page"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Start Planning</Button></Link></div></div></section>
    </>
  );
}
