import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, MapPin, Sun, Building, TreePalm } from "lucide-react";
export const metadata: Metadata = { title: "Johannesburg & Kruger — ArcTravel", description: "Africa's economic hub paired with Kruger National Park — one of the best safari destinations on the continent." };
const highlights = [
  { icon: Building, title: "Joburg City Life", desc: "Explore Maboneng, Soweto, the Apartheid Museum, and the vibrant arts and food scene of South Africa's largest city." },
  { icon: TreePalm, title: "Kruger National Park", desc: "One of Africa's premier game reserves — self-drive or guided safaris with incredible wildlife viewing year-round." },
  { icon: MapPin, title: "Panorama Route", desc: "Blyde River Canyon, Bourke's Luck Potholes, and God's Window — spectacular scenery on the drive to Kruger." },
  { icon: Building, title: "Sandton & Shopping", desc: "Africa's richest square mile — luxury malls, fine dining, and the stock exchange. Great for business travellers." },
];
const tips = ["Best time for Kruger: May to October (dry season, best wildlife viewing)", "Joburg is a driving city — arrange a car or driver for convenience", "Kruger is about 4-5 hours' drive from Joburg; we can arrange flights to Skukuza", "Malaria prophylaxis recommended for Kruger visits", "South Africa requires a valid passport with 2 blank pages"];
export default function JohannesburgKrugerPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#4a3520] via-[#5a4530] to-[#3a2510] py-20 sm:py-24"><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><div className="mb-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-medium text-white/80"><MapPin className="h-3 w-3" />South Africa — Gauteng & Mpumalanga</div><h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Johannesburg &amp; Kruger</h1><p className="mt-4 text-lg text-white/75">Africa's economic hub paired with one of the continent's best safari destinations.</p><Link href="/book?destination=Johannesburg+%26+Kruger&notes=Joburg+and+Kruger+destination+page" className="mt-8 inline-block"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer">Plan Your Trip <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-center">City & Safari Combo</h2><p className="mt-2 text-center text-muted-foreground">The best of urban South Africa and the wild</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{highlights.map((h) => (<div key={h.title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-accent/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent transition-colors group-hover:bg-accent group-hover:text-white"><h.icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{h.title}</h3><p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{h.desc}</p></div>))}</div></div></section>
      <section className="bg-muted/50 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 mb-6"><Sun className="h-5 w-5 text-accent" /><h2 className="text-2xl font-bold">Travel Tips</h2></div><ul className="space-y-3">{tips.map((t) => (<li key={t} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" /><span className="text-sm text-muted-foreground">{t}</span></li>))}</ul></div></div></section>
      <section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-accent/20 bg-accent/[0.02] p-8 text-center sm:p-12"><TreePalm className="mx-auto h-10 w-10 text-accent" /><h2 className="mt-4 text-2xl font-bold">City + Safari Combo?</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">Tell us how many days and what you want to prioritise — we'll build the perfect itinerary.</p><Link href="/book?destination=Johannesburg+%26+Kruger&notes=Joburg+and+Kruger+destination+page"><Button size="lg" className="bg-[#ff8912] text-white hover:bg-[#e67a00] shadow-lg shadow-[#ff8912]/25 active:scale-[0.97] transition-all cursor-pointer mt-6">Get Started</Button></Link></div></div></section>
    </>
  );
}
